/* FF4 source-port — interpreted module for func_8012BB68.
 * Ground truth: src/func_8012BB68.c (byte-verified).
 * Primitives: port/include/ff4_window.h.
 */
#include "ff4_window.h"
void func_8012BB68(void)
{
    cell_push_c8_d58();
    row_read(0x3F);
    if (sel(2) != 0)
        return;
    row_info(0x48);
    tail(0x4B);
    row_sync();
    row_open();
    func_80120A0C();
    row_close();
    row_done();
    cell_cursor_dec();
    cell_push_c8_d58(3);
    cell_tick_dbl();
    cell_flags_repack2();
    cell_tick_dbl();
    cell_flags_repack2();
    cell_tick_dbl();
    cell_flags_repack2();
    cell_tick_dbl();
    row_read(4);
    cell_tick_or(cell_state(0x34));
    cell_put(0x45);
    latch(0xE);
    shop_rows_37();
    shop_rows_37();
    shop_rows_37();
    shop_rows_37();
    row_close2();
    row_prep(0x20);
    row_read2(0x4B);
    sep_a();
    cell_peek0(cell_state(0x29));
    cell_put_hi9(0x4E);
    sep_a();
    cell_pos_fwd(0x40);
    cell_put_hi9(0x51);
    row_prep_close();
    page(0x48);
    cell_fmt2(0x4B);
    row_open();
    row_sync();
    func_80123320();
    row_done();
    row_close();
    tail(0x48);
    row_info(0x4B);
    row_prep(0x20);
    row_read2(0x51);
    sep_a();
    cell_pos_fwd(0x42);
    row_prep_close();
    latch(0x49);
    cell_pull_c8();
    latch(0x51);
    cell_pull_c8();
    cell_pull_c8(2);
    cell_pull_c8(0x42);
    latch(0x4E);
    cell_pull_c8();
    latch(0x40);
    cell_pull_c8();
    latch(0xC7);
    cell_pull_c8();
    cell_pull_c8(0xE);
    cell_pull_c8(0x4E);
    row_prep(0x20);
    page(0x51);
    cell_step();
    cell_step();
    row_sync2(0x46);
    draw_pad(7);
    config_rows_5a();
    row_sync2(0x50);
    draw_pad(9);
    config_rows_5a();
    row_sync2(0x86);
    draw_pad(0xB);
    config_rows_5a();
    row_sync2(0x90);
    draw_pad(0xD);
    config_rows_5a();
    row_prep_close();
    return;
}
