/* intro_strings.h - GENERATED by tools/rip/intro_pack.py */
#ifndef INTRO_STRINGS_H
#define INTRO_STRINGS_H

#include <stddef.h>

typedef struct { const char *file; const char *text; } intro_card_t;

static const intro_card_t g_intro_cards[] = {
    { "prologue_1.rgba", "Crew:Why are we robbing crystals from innocent people? Crew:That's our duty. Crew:Do we really have to keep doing this?" },
    { "prologue_1.rgba", "Crew:Captain! Crew:We can't stand doing this anymore! Cecil:Listen! Possessing the crystal is an essential factor for our prosperity. Moreover, His Majesty judged that Mysidians know too much about the secret of the crystal. We are the Red Wings, the air force of the Kingdom Baron! The Royal Command is absolute. Crew:Captain!" },
    { "prologue_1.rgba", "Crew:Monsters!!" },
    { "prologue_1.rgba", "Crew:Ouch! Cecil:You Okay? Crew:More coming! Cecil:Watch out!" },
    { "prologue_2.rgba", "You are entering into my realm, the Zemus-Zone. No one can ever escape from my minions! Perish in the Darkness before you reach me." },
    { "prologue_2.rgba", "Crew:We are over Baron! Cecil:Make a landing." },
    { "prologue_2.rgba", "Baigan:Oh, Cecil! Is it the Crystal of Water? Cecil:But Mysidians were so helpless. Baigan:What are you trying to say? This way, Cecil." },
    { "prologue_2.rgba", "Baigan:Please wait here." },
    { "prologue_2.rgba", "Baigan:Your Majesty! I'm afraid Cecil has developed quite a rebellious air. King:Truly!? Well done, Baigan! We must do something. Call him in! Baigan:Yes, Your Majesty." },
    { "prologue_2.rgba", "Baigan:Cecil! His Majesty summons you. Please come in." },
    { "prologue_2.rgba", "King:We thank you for successfully completing the mission. Now, where is it? Cecil:Here, My Liege." },
    { "prologue_2.rgba", "Hand over the crystal." },
    { "prologue_2.rgba", "Baigan:Real crystal… King:Good! Cecil…… You may leave now." },
    { "prologue_2.rgba", "Cecil:……" },
    { "prologue_2.rgba", "Cecil:We do not understand the meaning of taking crystals away from honest people. King:Disobeying me? Cecil:No, I don't. King:We do know of your discontent, Cecil. If you cannot trust me, I can no longer place the Red Wings in your command. You are dismissed from your post!" },
};

static const int g_intro_cards_n = 15;
#endif