#!/usr/bin/env python3
"""decomp_status.py — Phase A progress report.

Scans the repo state and writes decomp/STATUS.md (plus stdout summary):
  matched   : expected/matched/*.o present (byte-verified C)
  real-C    : src/*.c without __asm__ body (C written, match pending)
  shell     : src/*.c with __asm__ body (not decompiled yet)
Also breaks progress down by address band so we can watch hot clusters.

Usage: python3 tools/decomp_status.py
"""
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASM = ROOT / "asm" / "nonmatchings" / "main"
SRC = ROOT / "src"
MATCHED = ROOT / "expected" / "matched"
LANES = {}
for raw in (ROOT / "expected" / "lanes.txt").read_text().splitlines():
    p = raw.split()
    if len(p) == 2:
        LANES[p[1]] = p[0]

states = Counter()
lanes = Counter()
bands = Counter()
for c in SRC.glob("*.c"):
    name = c.stem
    if not re.match(r"func_(?:800|801)[0-9A-F]+", name):
        continue
    if (MATCHED / f"{name}.o").exists():
        states["matched"] += 1
    elif "__asm__" in c.read_text():
        states["shell"] += 1
    else:
        states["real-C"] += 1
    lanes[LANES.get(name, "?")] += 1
    band = "0x" + name[5:9]
    bands[band] += 1

total = sum(states.values())
pct = lambda k: f"{100.0 * states[k] / total:.1f}%" if total else "0%"
rows = [
    "| state | count | % |",
    "|---|---|---|",
    f"| byte-verified (matched C) | {states['matched']} | {pct('matched')} |",
    f"| C written, match pending | {states['real-C']} | {pct('real-C')} |",
    f"| asm shell (to do) | {states['shell']} | {pct('shell')} |",
    f"| **total** | {total} | 100% |",
]
lane_rows = [f"| {k} | {v} |" for k, v in sorted(lanes.items())]
band_rows = [f"| {k} | {v} |" for k, v in sorted(bands.items())]

md = [
    "# FF4 (SLUS_013.60) — Phase A decomp status",
    "",
    f"Generated by `tools/decomp_status.py` — {total} functions in main EXE text.",
    "",
    "## Overall",
    "",
    "\n".join(rows),
    "",
    "## By toolchain lane (target compiler for byte-match)",
    "",
    "| lane | funcs |",
    "|---|---|",
    *lane_rows,
    "",
    "## By address band",
    "",
    "| band | funcs |",
    "|---|---|",
    *band_rows,
    "",
]
(ROOT / "decomp").mkdir(exist_ok=True)
(ROOT / "decomp" / "STATUS.md").write_text("\n".join(md) + "\n")
print(f"TOTAL {total} | matched {states['matched']} | "
      f"real-C {states['real-C']} | shell {states['shell']} | "
      f"(C complete: {states['matched'] + states['real-C']} = "
      f"{pct('matched')} matched, {100.0 * (states['matched'] + states['real-C']) / total:.1f}% C-written)")
print("wrote decomp/STATUS.md")